### ISSUE TITLE
init.d script error on debian jessie

### ISSUE THREAD

**Issue by garlofrank** [soar/ipset-persistent#1]
Hi, I get errors for /etc/init.d/ipset-persistent script.

Debian Jessie OS

XXXXX$ sudo service ipset-persistent save
[....] Saving ipset sets.../etc/init.d/ipset-persistent: 96: [: yes: unexpected operator
done.

But,,,, the sets are saved ! ... 
¿?

Another error I think is for parameter IP_SPLIT_CONFIG
Set to yes, only one file is created (sets).

Thanks for the script and sorry for my english.

**Comment by garlofrank** [comment]
I've been reading a bit more about debian jessie.
Now the init.d script for iptables-persistent is called netfilter-persistent and this script calls other scripts in /usr/share/netfilter-persistent/plugins.d/

**Comment by szepeviktor** [comment]
Here is a `netfilter-persistent` compatible package
https://github.com/szepeviktor/debian-server-tools/tree/master/security/myattackers-ipsets/ipset-persistent/debian
As a package: https://github.com/szepeviktor/szepeviktor.github.io/tree/master/debian/pool/main/i/ipset-persistent

**Comment by soar** [comment]
@garlofrank thank you. I wrote this script on wheezy - so yes, double `==` should be changed to `=` in two places.

Thanks to @lingonl and @xaionaro - should be fixed now.
